/notes:
  get:
    tags:
      - "note"
    summary: "List of all notes"
    description: "Returns all notes"
    # operationId: "getNoteById"
    produces:
      - "application/xml"
      - "application/json"
    # parameters:
    # - name: "noteId"
    #   in: "path"
    #   description: "ID of note to return"
    #   required: true
    #   type: "integer"
    #   format: "int64"
    responses:
      200:
        description: "successful operation"
        # schema:
        # $ref: "#/definitions/Note"
      400:
        description: "Invalid ID supplied"
      404:
        description: "Note not found"
    # security:
    # - api_key: []
  post:
    tags:
      - "note"
    summary: "Create a note in the store with form data"
    description: ""
    operationId: "createNoteWithForm"
    consumes:
      - "application/x-www-form-urlencoded"
    produces:
      - "application/xml"
      - "application/json"
    parameters:
      - name: "title"
        in: "formData"
        description: "title of the note"
        required: true
        type: "string"
      - name: "content"
        in: "formData"
        description: "Content of the note"
        required: false
        type: "string"
    responses:
      405:
        description: "Invalid input"
    # security:
    # - petstore_auth:
    #   - "write:notes"
    #   - "read:notes"

/notes/{noteId}:
  get:
    tags:
      - "note"
    summary: "Find note by ID"
    description: "Returns a single note"
    operationId: "getNoteById"
    produces:
      - "application/xml"
      - "application/json"
    parameters:
      - name: "noteId"
        in: "path"
        description: "ID of note to return"
        required: true
        type: "integer"
        format: "int64"
    responses:
      200:
        description: "successful operation"
        # schema:
        # $ref: "#/definitions/Note"
      400:
        description: "Invalid ID supplied"
      404:
        description: "Note not found"
    # security:
    # - api_key: []
  patch:
    tags:
      - "note"
    summary: "Updates a note in the store with form data"
    description: ""
    operationId: "updateNoteWithForm"
    consumes:
      - "application/x-www-form-urlencoded"
    produces:
      - "application/xml"
      - "application/json"
    parameters:
      - name: "noteId"
        in: "path"
        description: "ID of note that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "name"
        in: "formData"
        description: "Updated name of the note"
        required: false
        type: "string"
      - name: "status"
        in: "formData"
        description: "Updated status of the note"
        required: false
        type: "string"
    responses:
      405:
        description: "Invalid input"
    # security:
    # - petstore_auth:
    #   - "write:notes"
    #   - "read:notes"
  delete:
    tags:
      - "note"
    summary: "Deletes a note"
    description: ""
    operationId: "deleteNote"
    produces:
      - "application/xml"
      - "application/json"
    parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "noteId"
        in: "path"
        description: "Note id to delete"
        required: true
        type: "integer"
        format: "int64"
    responses:
      400:
        description: "Invalid ID supplied"
      404:
        description: "Note not found"
    # security:
    # - notestore_auth:
    #   - "write:notes"
    #   - "read:notes"
